spring:
  rabbitmq:
    host: 119.29.175.113
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 300
        max-concurrency: 300
server:
  port: 8080
